---
title: Your Site Title
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Your site description goes here.
baseurl: ''
url: ''
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- node_modules
- package.json
- package-lock.json
- README.md
- ".gitignore"
