title: Your Site Title
email: your-email@example.com
description: >-
  Your site description goes here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
  pages:
    output: true

# Exclude from processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore 